In [1]:
l = [334, -1234, 676, 85]

In [2]:
l

[334, -1234, 676, 85]

In [3]:
import numpy as np

In [5]:
a= np.array(l)

In [6]:
a

array([  334, -1234,   676,    85])

In [7]:
l.pop()

85

In [8]:
l

[334, -1234, 676]

In [9]:
a.mean()

-34.75

In [10]:
# Slicing arrays

In [11]:
a

array([  334, -1234,   676,    85])

In [12]:
a[2:]

array([676,  85])

In [13]:
b = a[2:4]

In [14]:
b

array([676,  85])

In [15]:
b[:] = 111

In [16]:
b

array([111, 111])

In [17]:
a # original elements of a changed due to assignments in b above. This will not happen in case of lists

array([  334, -1234,   111,   111])

In [18]:
a.copy()

array([  334, -1234,   111,   111])

In [19]:
c= a.copy()

In [20]:
c

array([  334, -1234,   111,   111])

In [21]:
c[0] = 10

In [22]:
c

array([   10, -1234,   111,   111])

In [23]:
a

array([  334, -1234,   111,   111])

In [25]:
d= l[:4]

In [26]:
d

[334, -1234, 676]

In [27]:
d[0] = 100

In [28]:
d

[100, -1234, 676]

In [29]:
l # no change to original list on above assignmet. No copy was created for the list

[334, -1234, 676]