In [1]:
#Data 
revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]
expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]

In [2]:
import numpy as np

In [ ]:
# Converting lists to arrays

In [3]:
r_array = np.array(revenue)

In [4]:
r_array

array([14574.49,  7606.46,  8611.41,  9175.41,  8058.65,  8105.44,
       11496.28,  9766.09, 10305.32, 14379.96, 10713.97, 15433.5 ])

In [5]:
e_array = np.array(expenses)

In [6]:
e_array

array([12051.82,  5695.07, 12319.2 , 12089.72,  8658.57,   840.2 ,
        3285.73,  5821.12,  6976.93, 16618.61, 10054.37,  3803.96])

---

In [7]:
# Profit for each month

In [8]:
profit= r_array - e_array

In [9]:
profit

array([ 2522.67,  1911.39, -3707.79, -2914.31,  -599.92,  7265.24,
        8210.55,  3944.97,  3328.39, -2238.65,   659.6 , 11629.54])

In [10]:
profit.round(2)   # rounding to 2 decimal places

array([ 2522.67,  1911.39, -3707.79, -2914.31,  -599.92,  7265.24,
        8210.55,  3944.97,  3328.39, -2238.65,   659.6 , 11629.54])

In [11]:
# Profit after tax for each month

In [12]:
profit_after_tax = profit.round(2)* 0.7

In [13]:
profit_after_tax

array([ 1765.869,  1337.973, -2595.453, -2040.017,  -419.944,  5085.668,
        5747.385,  2761.479,  2329.873, -1567.055,   461.72 ,  8140.678])

In [14]:
# Profit margin for each month

In [15]:
profit_margin = profit_after_tax / r_array *100

In [16]:
profit_margin

array([ 12.11616324,  17.58995643, -30.13969838, -22.23352417,
        -5.21109615,  62.74388559,  49.99343266,  28.27619856,
        22.60844884, -10.89749207,   4.30951365,  52.74680403])

In [17]:
profit_margin.round(2)

array([ 12.12,  17.59, -30.14, -22.23,  -5.21,  62.74,  49.99,  28.28,
        22.61, -10.9 ,   4.31,  52.75])

In [18]:
#Good months : Profit after tax > Mean of profit after tax for the year

In [19]:
mean_profit = profit_after_tax.round(2).mean()

In [21]:
mean_profit.round(2)

1750.68

In [24]:
good_months = profit_after_tax.round(2) > mean_profit.round(2)

In [25]:
good_months

array([ True, False, False, False, False,  True,  True,  True,  True,
       False, False,  True])

In [26]:
good_months_final = profit_after_tax.round(2)[good_months]

In [27]:
good_months_final # using numpy arrays

array([1765.87, 5085.67, 5747.38, 2761.48, 2329.87, 8140.68])

In [36]:
pat_list = list(profit_after_tax.round(2))


In [37]:
pat_list

[1765.87,
 1337.97,
 -2595.45,
 -2040.02,
 -419.94,
 5085.67,
 5747.38,
 2761.48,
 2329.87,
 -1567.06,
 461.72,
 8140.68]

In [39]:
gpf= []  #finding good months based on lists and using for loop
for i in pat_list:
    if  i.round(2) > mean_profit.round(2):
        gpf.append(i.round(2))
print(gpf)

[1765.87, 5085.67, 5747.38, 2761.48, 2329.87, 8140.68]


In [44]:
good_months_array = np.array(gpf)

In [45]:
good_months_array

array([1765.87, 5085.67, 5747.38, 2761.48, 2329.87, 8140.68])

In [46]:
#Bad months : Profit after tax < Mean of profit after tax for the year

In [47]:
bad_months = profit_after_tax.round(2) < mean_profit.round(2)
bad_months

array([False,  True,  True,  True,  True, False, False, False, False,
        True,  True, False])

In [48]:
bad_months_final = profit_after_tax.round(2)[bad_months].round(2)
bad_months_final

array([ 1337.97, -2595.45, -2040.02,  -419.94, -1567.06,   461.72])

In [ ]:
# Best month

In [49]:
best_month = profit_after_tax.round(2).max()
best_month

8140.68

In [71]:
for i in range(0, len(profit_after_tax.round(2))):
    if profit_after_tax.round(2)[i] == best_month:
        print("Best month is : ", i+1)

Best month is :  12


In [56]:
# Worst Month

In [57]:
worst_month = profit_after_tax.round(2).min()
worst_month

-2595.45

In [72]:
for i in range(0, len(profit_after_tax.round(2))):
    if profit_after_tax.round(2)[i] == worst_month:
        print("Worst month is : ", i+1)

Worst month is :  3


In [59]:
# Converting all arrays to in '000'

In [68]:
revenue_thousands = (r_array / 1000).astype(int)
expenses_thousands = (e_array / 1000).astype(int)
profit_thousands = (profit / 1000).astype(int)
profit_after_tax_thousands = (profit_after_tax / 1000).astype(int)

In [70]:
print("Revenue in thousands : ", revenue_thousands), 
print("Expenses in thousands : ",expenses_thousands), 
print("Profit in thousands : ",profit_thousands), 
print("Profit after tax in thousands : ", profit_after_tax_thousands)

Revenue in thousands :  [14  7  8  9  8  8 11  9 10 14 10 15]
Expenses in thousands :  [12  5 12 12  8  0  3  5  6 16 10  3]
Profit in thousands :  [ 2  1 -3 -2  0  7  8  3  3 -2  0 11]
Profit after tax in thousands :  [ 1  1 -2 -2  0  5  5  2  2 -1  0  8]


In [73]:
l1= [20, 'a', 21, 'b', 22, 'c', 23, 'd', 24, 'e', 25, 'f']

In [74]:
l1[1::2]

['a', 'b', 'c', 'd', 'e', 'f']

In [75]:
l1[1:12:2]

['a', 'b', 'c', 'd', 'e', 'f']

In [76]:
l1[-1:-12:-2]

['f', 'e', 'd', 'c', 'b', 'a']